import type { Metadata } from 'next'
import './globals.css'
import { AuthProvider } from '@/components/providers/auth-provider'
import Sidebar from '@/components/layout/Sidebar'
import Footer from '@/components/layout/Footer'
import { geistSans, geistMono } from '@/lib/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Lobster&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-sidebar`}
      >
        <AuthProvider>
          <div className="min-h-svh w-full flex">
            <Sidebar />
            <main className="flex-1 min-w-0">
              <div className="mx-auto max-w-7xl p-4 md:p-6 lg:p-8">
                {children}
              </div>
              <Footer />
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
